### PR TITLE
Reverted to java 8 to fix build. Plus other fixes. no coding changes

### PR DESCRIPTION
**Pull request by firestorm942**
updated to latest spigot version(1.19.2) -- tested
Added api-version to plugin.yml to keep spigot/paper from complaining.
Reverted to java 8 to fix build
Updated to latest SNAPSHOT of ProtocolLib

### CODE REVIEW

**Comment by lenis0012** [comment]
I changed it to java 11? I dont even remember this

**Comment by lenis0012** [comment]
that is.. a problem

**Comment by lenis0012** [comment]
Btw, I see you removed the updater modules. They are starting to become a pain for people forking the project. The idea is that you build with either one of the profiles (e.g., `mvn package -Pspigot` or `mvn package -Pbukkit`). But I am planning to add a more graceful fallback very soon.

**Comment by firestorm942** [comment]
I see about the build. All good, Most of my changes were implemented anyway. So I decided that there was no point in keeping this one open. :)

**Pull request closed without merging**
