### PR TITLE
resolved the api-version warning when used in papermc server, and fix a mvn package phase warning

### PR DESCRIPTION
**Pull request by wangzhizhou**
- ignore the MacOS .DS_Store file from the SVC
- resolve the warning when used as a papermc plugin: `Legacy plugin LoginSecurity v3.1.1 does not specify an api-version.`
- resolve a mvn package waring

### CODE REVIEW

**Comment by wangzhizhou** [comment]
https://github.com/lenis0012/LoginSecurity-2/issues/289

**Comment by lenis0012** [comment]
this breaks compatability with MC 1.13-1.18.x

**Comment by wangzhizhou** [comment]
> this breaks compatability with MC 1.13-1.18.x

Ok, I get it. Thx

**Comment by lenis0012** [comment]
@wangzhizhou as a workaround I think I could set api-version 1.13.
That should work on 1.8 - 1.19.4 and at least not show the "legacy" warning

**Comment by wangzhizhou** [comment]
> @wangzhizhou as a workaround I think I could set api-version 1.13. That should work on 1.8 - 1.19.4 and at least not show the "legacy" warning

May I have a try on my fork of your repo，It should be ok

**Comment by BRGustavoRibeiro** [comment]
Any updates on this warning issue?

**Comment by lenis0012** [comment]
@BRGustavoRibeiro should be fixed in version 3.2.0

**Pull request closed without merging**
